// import mockBooks from 'books-mock-api';
export const books = [
  {
    title: "Data Science",
    id: 1,
    url: "https://th.bing.com/th/id/OIP.KqRh84bIXZRJsMwBN5rJ4AHaJ_?pid=ImgDet&rs=1",
    author: "Austen, Jane",
    year_written: 1814,
    edition: "Penguin",
    price: 18.2,
  },
  {
    title: "Macmillan English Fluency Book",
    id: 2,
    url: "https://th.bing.com/th/id/OIP.ekvfc1pudJ7XyXcbrvPWEgHaJf?pid=ImgDet&rs=1",
    author: "Tolstoy, Leo",
    year_written: 1865,
    edition: "Penguin",
    price: 12.7,
  },
  {
    title: "Fundamentals of Information Technology",
    id: 3,
    url: "https://th.bing.com/th/id/OIP.KqRh84bIXZRJsMwBN5rJ4AHaJ_?pid=ImgDet&rs=1",
    author: "Tolstoy, Leo",
    year_written: 1875,
    edition: "Penguin",
    price: 13.5,
  },
  {
    title: "ETHICS in Healthcare",
    id: 4,
    url: "https://th.bing.com/th/id/OIP.ODO3ysVlZHC0dRgDtp62PwHaK2?pid=ImgDet&rs=1",
    author: "Woolf, Virginia",
    year_written: 1925,
    edition: "Harcourt Brace",
    price: 25,
  },
  {
    title: "The Hours",
    id: 5,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Cunnningham, Michael",
    year_written: 1999,
    edition: "Harcourt Brace",
    price: 12.35,
  },
  {
    title: "Impacts Of Technology",
    id: 6,
    url: "https://booksrun.com/image-loader/350/https:__m.media-amazon.com_images_I_51wOgpJ-8TL.jpg",
    author: "Twain, Mark",
    year_written: 1865,
    edition: "Penguin",
    price: 5.76,
  },
  {
    title: "CYBERLAW",
    id: 7,
    url: "https://th.bing.com/th/id/OIP.8EuUOSbtrwcyWRR-IjxIRwAAAA?pid=ImgDet&rs=1",
    author: "Dickens, Charles",
    year_written: 1870,
    edition: "Random House",
    price: 5.75,
  },
  {
    title: "DNA Science",
    id: 8,
    url: "https://th.bing.com/th/id/OIP.ODO3ysVlZHC0dRgDtp62PwHaK2?pid=ImgDet&rs=1",
    author: "Twain, Mark",
    year_written: 1862,
    edition: "Random House",
    price: 7.75,
  },
  {
    title: "A Room of One's Own",
    id: 9,
    url: "https://miro.medium.com/max/1200/1*zBRkcBbsjWzcPjtcxqhb3Q.jpeg",
    author: "Woolf, Virginia",
    year_written: 1922,
    edition: "Penguin",
    price: 29,
  },
  {
    title: "Technology vs Humanity",
    id: 10,
    url: "https://th.bing.com/th/id/OIP.8EuUOSbtrwcyWRR-IjxIRwAAAA?pid=ImgDet&rs=1",
    author: "Rowling, J.K.",
    year_written: 2000,
    edition: "Harcourt Brace",
    price: 19.95,
  },
  {
    title: "Business Studies",
    id: 11,
    url: "https://th.bing.com/th/id/R.6a917ffaab8f35a62abfab9b716797aa?rik=ad1U7rUeloAQ3g&riu=http%3a%2f%2fwww.gcsebooks.com%2fwp-content%2fuploads%2f2021%2f02%2fCambridge-IGCSE-Business-Studies-Teachers-Resource-CD-ROM-Cambridge-International-IGCSE.jpg&ehk=AVvVZ4roPaI2iDcsPA85Z1qz9v3rhM2SSw9ZxT5vngs%3d&risl=&pid=ImgRaw&r=0&sres=1&sresct=1",
    author: "Marquez",
    year_written: 1967,
    edition: "Harper  Perennial",
    price: 14.0,
  },
  {
    title: "BLOCKCHAIN TECHNOLOGY Revolution",
    id: 12,
    url: "https://kbimages1-a.akamaihd.net/2c786954-48d6-486e-bcbe-d4725d5ef797/353/569/90/False/blockchain-technology-revolution-the-next-big-thing-to-change-everything-for-everyone.jpg",
    author: "Shakespeare",
    year_written: 1603,
    edition: "Signet  Classics",
    price: 7.95,
  },
];

// export const newBooks= mockBooks.getBooks();
